### ISSUE TITLE
does it not support Alhambra II?

### ISSUE THREAD

**Issue by agnunez** [FPGAwars/apio-ide#28]
Hi, after installing Atom and APIO-IDE, it only offer Icezum Alhambra, version II does not appears as option. I am using IceStudio without problem with A-II and also check apio for lsftdi and recognize this version.

Thanks

**Comment by jjchico** [comment]
I made some changes to my fork in order to support apio 0.4.0 and the new boards. You may try my branch at:
https://github.com/jjchico/apio-ide/tree/apio040-support

Overall instructions:
1) Clone my repo:

        git clone https://github.com/jjchico/apio-ide.git

2) Enter the directory and checkout the modified branch:

        cd apio-ide
        git checkout apio040-support

3) Link the modified package to your Atom in development mode:

        apm link --dev

4) Open an Atom development branch and test

    View -> Developer -> Open in dev mode ...

**Comment by jjchico** [comment]
@agnunez Apio 4.0 support is now merged upstream. It will be available in Atom's repository soon, I guess.

**Comment by juseruin16** [comment]
Hey, I´m new working with APIO and FPGA's so please if you solved this problem let me now, I tried with jjchico's link but I think isn't working anymore

**Comment by Obijuan** [comment]
Apio-ide is now archived
